pipeline {
    agent any
    environment {
      RELEASE= "21.12"
    }
    stages {
        stage('Build') {
            agent any
            environment {
                LOG_LEVEL='INFO'
            }
            steps {
                echo "Building release ${RELEASE} with log level ${LOG_LEVEL}..."
            }
        }
        stage('Test') {
            steps {
                echo "Testing release ${RELEASE}..."
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploying release ${RELEASE} to environment"
            }
        }        
    }
}
